### ISSUE TITLE
Some question About HK RTSP

### ISSUE THREAD

**Issue by JacobRachel** [mengzhidaren/VlcPlayer#4]
Hi, 我使用海康的RTSP流时，不能够播放，然而使用博主提供的那几个公开流没有任何问题，当我使用海康的流时，
 I/VideoMediaLogic: StateChanged   =0
 I/VideoMediaLogic: Playing
 I/: 延迟时间=378
 I/VideoMediaLogic: Media.Event.type=2   eventgetParsedStatus=0
 E/VLC: [9d921628/69db] core decoder: buffer deadlock prevented
 I/VideoMediaLogic: MediaPlayer.Event.Buffering100.0

can you help me solve this problem

**Comment by mengzhidaren** [comment]
你提供一个同码率的开源测试地址吗  测码流要多端配合一点点调试我也帮不了太多
